name: Terraform CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    working-directory: ./terraform

jobs:
  check-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository code
        uses: actions/checkout@v4

      - name: Authenticate to GCP via Workload Identity
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialise terraform
        run: terraform init

      - name: Validation of terraform
        run: terraform validate

      - name: Security Scan
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
          output_format: cli
          soft_fail: true

      - name: Terraform Plan
        run: terraform plan
        
