name: Terraform CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    working-directory: ./terraform

jobs:
  check-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialise terraform
        run: terraform init

      - name: Validation of terraform
        run: terraform validate

      - name: Security Scan
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terrafrom
          output_format: cli
          soft_fail: true

      - name: Terraform Plan
        env:
          GOOGLE_CREDENTIALS: '{"type": "service_account", "project_id": "mock-project-id"}' 
        run: terraform plan
        
